spring:
  profiles:
    active: local
---
spring:
  config:
    import: db-mysql.yaml
    activate:
      on-profile: local
  batch:
    jdbc:
      initialize-schema: never
      isolation-level-for-create: default
    job:
      enabled: true
      names: apiJob
  jpa:
    hibernate:
      ddl-auto: none
      format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
---
spring:
  config:
    import: db-h2.yaml
    activate:
      on-profile: h2
  batch:
    jdbc:
      initialize-schema: embedded

