spring:
  profiles:
    active: local
---
spring:
  batch:
    jdbc:
      initialize-schema: never
    job:
      enabled: true
      names: ${job.name:NONE}
  config:
    import: db-mysql.yaml
    activate:
      on-profile: local
  jpa:
    hibernate:
      ddl-auto: none
      format_sql: true
    open-in-view: true


logging:
  level:
    org.hibernate.SQL: debug
---
spring:
  config:
    import: db-h2.yaml
    activate:
      on-profile: h2
  batch:
    jdbc:
      initialize-schema: embedded

