spring:
  config:
    import: db.yaml

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: none # validate # ddl option
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 500