spring:
  profiles:
    active: local
---
spring:
  config:
    import: db-mysql.yaml
    activate:
      on-profile: local
  batch:
    jdbc:
      initialize-schema: never
    job:
      enabled: false
---
spring:
  config:
    import: db-h2.yaml
    activate:
      on-profile: h2
  batch:
    jdbc:
      initialize-schema: embedded

